[build]
  command = "npm run build"
  publish = "dist"

# Tell Netlify not to scan these keys - they're meant to be public in frontend apps
[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

